export const productConstants = {
  GET_ALL_PRODUCT_REQUEST:
    "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS:
    "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE:
    "GET_ALL_PRODUCT_FAILURE",
};
