export const productConstants = {
  GET_ALL_PRODUCT_REQUEST:
    "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS:
    "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE:
    "GET_ALL_PRODUCT_FAILURE",
};
export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  DELETE_PRODUCT_REQUEST:
    "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS:
    "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE:
    "DELETE_PRODUCT_FAILURE",
  INCREASE_PRODUCT_CART_REQUEST:
    "INCREASE_PRODUCT_CART_REQUEST",
  INCREASE_PRODUCT_CART_SUCCESS:
    "INCREASE_PRODUCT_CART_SUCCESS",
  INCREASE_PRODUCT_CART_FAILURE:
    "INCREASE_PRODUCT_CART_FAILURE",
  DECREASE_PRODUCT_CART_REQUEST:
    "DECREASE_PRODUCT_CART_REQUEST",
  DECREASE_PRODUCT_CART_SUCCESS:
    "DECREASE_PRODUCT_CART_SUCCESS",
  DECREASE_PRODUCT_CART_FAILURE:
    "DECREASE_PRODUCT_CART_FAILURE",
  DELETE_ALL_PRODUCTS_REQUEST:
    "DELETE_ALL_PRODUCTS_REQUEST",
  DELETE_ALL_PRODUCTS_REQUEST_SUCCESS:
    "DELETE_ALL_PRODUCTS_REQUEST_SUCCESS",
  DELETE_ALL_PRODUCTS_REQUEST_FAILURE:
    "DELETE_ALL_PRODUCTS_REQUEST_FAILURE",
};
